### ISSUE TITLE
Could you share pre-trained models?

### ISSUE THREAD

**Issue by nooooonee** [ashafahi/free_adv_train#2]
Could you share your pre-trained models?  Of course, we can train them from scratch, but it will be largely convenient if pre-trained models can be provided.  Thanks in advance.

**Comment by ashafahi** [comment]
Hi,

Sorry for the huge delay. Sure. [Here](https://drive.google.com/drive/folders/1x8LvqFzNweAvnlTFV13nRgX9X3Jjp-yQ?usp=sharing) you can find the pre-trained CIFAR-10 model (eps=8, m=8).

**Comment by pengdan1129** [comment]
noted with many thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ashafahi <notifications@github.com>
发送时间: Tuesday, August 6, 2019 12:23:42 AM
收件人: ashafahi/free_adv_train <free_adv_train@noreply.github.com>
抄送: lepangdan <lepangdan@outlook.com>; Author <author@noreply.github.com>
主题: Re: [ashafahi/free_adv_train] Could you share pre-trained models? (#2)


Hi,

Sorry for the huge delay. Sure. Here<https://drive.google.com/drive/folders/1x8LvqFzNweAvnlTFV13nRgX9X3Jjp-yQ?usp=sharing> you can find the pre-trained CIFAR-10 model (eps=8, m=8).

―
